name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace API key placeholder
      run: |
        sed -i 's/__NOCODB_API_KEY__/${{ secrets.NOCODB_APIKEY }}/g' index.html

    - name: Deploy to server
      run: |
        # Add your deployment script here
        echo "Deploying..."
